[Appearance]
colors_scheme_name=Caelestia

[Paths]
# This section is generally left empty for color schemes

[ColorScheme]
# Format: [Active], [Disabled], [Inactive]
# Roles: Window, WindowText, Base, AlternateBase, ToolTipBase, ToolTipText, Text, Button, ButtonText, BrightText, Link, LinkVisited, Highlight, HighlightedText, Q3ListViewBorder, Q3ControlLow, Midlight, Mid, Dark, Shadow, Highlight (secondary), Link (secondary)

active_colors=#ff101442, #ffa5a8d5, #ff06092f, #ff101442, #ff101442, #ffe3e3ff, #ffe3e3ff, #ff151a4c, #ffe3e3ff, #fffbf8ff, #ff6186d0, #ff6d77dd, #ff8fabff, #ff002872, #ff101442, #ff101442, #ff1b2055, #ff101442, #ff06092f, #ff000000, #ff8fabff, #ff6186d0
disabled_colors=#ff101442, #ff6f729d, #ff06092f, #ff101442, #ff101442, #ff6f729d, #ff6f729d, #ff151a4c, #ff6f729d, #fffbf8ff, #ff6186d0, #ff6d77dd, #ff414a66, #ff101442, #ff101442, #ff101442, #ff1b2055, #ff101442, #ff06092f, #ff000000, #ff414a66, #ff6186d0
inactive_colors=#ff101442, #ffa5a8d5, #ff06092f, #ff101442, #ff101442, #ffe3e3ff, #ffe3e3ff, #ff151a4c, #ffe3e3ff, #fffbf8ff, #ff6186d0, #ff6d77dd, #ff8fabff, #ff002872, #ff101442, #ff101442, #ff1b2055, #ff101442, #ff06092f, #ff000000, #ff8fabff, #ff6186d0
