{pkgs, ...}:
with pkgs; [
    vim
    git
    kitty
    app2unit
    upower
    calibre
    foot
    android-file-transfer
    signal-desktop
    scrcpy
    equibop
    cliphist
    wl-clipboard
    hyprpicker
    trash-cli
    jq
    btop
    eza
    fastfetch
    lm_sensors
    strawberry
    kdePackages.kate
    kdePackages.qt6ct
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kdePackages.qtsvg
    kdePackages.kio-fuse
    kdePackages.kio-extras
    kdePackages.plasma-workspace
]
